import type { Metadata } from "next";
import "./globals.css";
import { notoSansJp } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${notoSansJp.className} text-sm md:text-base`}>
        {children}
      </body>
    </html>
  );
}
